Check that dependent scripts are present.

diff --git a/build/history/mkchangelogs b/build/history/mkchangelogs
--- a/build/history/mkchangelogs
+++ b/build/history/mkchangelogs
@@ -141,6 +141,18 @@ then
   exit 1
 fi
 
+if [[ ! -f ${TOOLPATH}/cvs2cl.pl ]]
+then
+  echo "$TOOLNAME : Can't find \"${TOOLPATH}/cvs2cl.pl\"."
+  exit 1
+fi
+
+if [[ ! -f ${TOOLPATH}/cl2html.awk ]]
+then
+  echo "$TOOLNAME : Can't find \"${TOOLPATH}/cl2html.awk\"."
+  exit 1
+fi
+
 if [ $0 -ef ./build/history/mkchangelogs ]
 then
   echo "$TOOLNAME : Can't use this script to get its own change log."
